/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=HC1-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/HC1 \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=HC1-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=HC2-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/HC2 \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=HC2-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=HC3-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/HC3 \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=HC3-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=HC4-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/HC4 \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=HC4-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA1-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA1/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA01-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA2-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA2/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA02-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA2-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA2/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA02-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA3-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA3/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA03-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA3-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA3/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA03-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA04-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA4/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA04-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA04-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA4/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA04-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA05-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA5/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA05-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA05-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA5/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA05-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA06-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA6/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA06-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA06-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA6/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA06-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA08-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA8/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA08-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA08-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA8/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA08-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA09-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA9/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA09-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA09-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA9/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA09-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA10-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA10/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA10-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA10-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA10/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA10-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA11-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA11/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA11-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA11-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA11/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA11-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA12-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA12/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA12-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA12-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA12/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA12-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA13-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA13/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA13-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA13-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA13/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA13-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA14-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA14/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA14-PBMC
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA14-SM \
                                                      --fastqs=/Bailab5/liuyi/RA/RA14/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA14-SM
/home/liuyi/biosoft/cellranger-2.2.0/cellranger count --id=RA15-PBMC \
                                                      --fastqs=/Bailab5/liuyi/RA/RA15/ \
                                                      --transcriptome=/Bailab5/liuyi/reference/refdata-cellranger-GRCh38-1.2.0 \
                                                      --sample=RA15-PBMC                                                                                                                                                                                                                      